In [14]:
import pandas as pd

df = pd.read_table('dataset/Fashion Landmark Detection Benchmark/Anno/list_landmarks_1000.txt', sep=' ')
df.fillna(-1, inplace=True)
df.head()

,image_name,clothes_type,variation_type,landmark_visibility_1,landmark_location_x_1,landmark_location_y_1,landmark_visibility_2,landmark_location_x_2,landmark_location_y_2,landmark_visibility_3,...,landmark_location_y_5,landmark_visibility_6,landmark_location_x_6,landmark_location_y_6,landmark_visibility_7,landmark_location_x_7,landmark_location_y_7,landmark_visibility_8,landmark_location_x_8,landmark_location_y_8
0,img/img_00000001.jpg,1,1,1,144,156,1,221,159,0,...,408.0,0.0,237.0,412.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,img/img_00000002.jpg,1,3,0,111,104,1,153,105,0,...,188.0,1.0,137.0,198.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,img/img_00000003.jpg,1,1,0,112,113,1,172,117,0,...,277.0,1.0,187.0,262.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,img/img_00000004.jpg,1,2,0,76,74,0,108,69,0,...,174.0,0.0,126.0,170.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,img/img_00000005.jpg,1,1,0,217,139,0,290,156,0,...,314.0,0.0,309.0,313.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0